
VCHAR   =/  UTF8-non-ascii

ctext   =/  UTF8-non-ascii

atext   =/  UTF8-non-ascii

qtext   =/  UTF8-non-ascii

text    =/  UTF8-non-ascii
             ; note that this upgrades the body to UTF-8

dtext   =/  UTF8-non-ascii
